"""added blog class on the model.py

Revision ID: 01256fd813fa
Revises: 787e22d1a79f
Create Date: 2020-09-28 08:43:41.979610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01256fd813fa'
down_revision = '787e22d1a79f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blogs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('blogg_title', sa.String(), nullable=True),
    sa.Column('blogg', sa.String(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blogs')
    # ### end Alembic commands ###
