"""changed the blog contents

Revision ID: 822f00b4cd86
Revises: 01256fd813fa
Create Date: 2020-09-28 08:49:23.039004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '822f00b4cd86'
down_revision = '01256fd813fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('blog_content', sa.String(), nullable=True))
    op.add_column('blogs', sa.Column('blog_title', sa.String(), nullable=True))
    op.drop_column('blogs', 'blogg_title')
    op.drop_column('blogs', 'blogg')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('blogg', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('blogs', sa.Column('blogg_title', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('blogs', 'blog_title')
    op.drop_column('blogs', 'blog_content')
    # ### end Alembic commands ###
