"""updated the database

Revision ID: 8f1605b0e634
Revises: c481d72e0163
Create Date: 2020-09-29 01:40:11.729946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f1605b0e634'
down_revision = 'c481d72e0163'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog', sa.Column('content', sa.String(), nullable=True))
    op.add_column('blog', sa.Column('title', sa.String(), nullable=True))
    op.drop_column('blog', 'blog_title')
    op.drop_column('blog', 'blog_content')
    op.add_column('users', sa.Column('bio', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('profile_pic_path', sa.String(), nullable=True))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column('users', 'profile_pic_path')
    op.drop_column('users', 'email')
    op.drop_column('users', 'bio')
    op.add_column('blog', sa.Column('blog_content', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('blog', sa.Column('blog_title', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('blog', 'title')
    op.drop_column('blog', 'content')
    # ### end Alembic commands ###
