"""updated the database

Revision ID: c481d72e0163
Revises: da9e5e0a1328
Create Date: 2020-09-29 01:25:54.133233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c481d72e0163'
down_revision = 'da9e5e0a1328'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscribers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('comments', 'image_path')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('image_path', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_table('subscribers')
    # ### end Alembic commands ###
